--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/Mrchlldev/Nickname
build-by-default: true
branches:
- main
projects:
  Nickname:
    path: ""
    libs:
    - src: jojoe77777/FormAPI/FormAPI
      version: ^1.0.0
...
